<a href="https://colab.research.google.com/github/kevin1786/20220702-Python-K/blob/main/20220730.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 使用 Teachable Machine 幫我們訓練好的模型

In [ ]:
!unzip model.zip

Archive:  model.zip
 extracting: keras_model.h5          
 extracting: labels.txt              


In [ ]:
from keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

# Load the model
model = load_model('keras_model.h5')

# Create the array of the right shape to feed into the keras model
# The 'length' or number of images you can put into the array is
# determined by the first position in the shape tuple, in this case 1.
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
# Replace this with the path to your image
image = Image.open('victor.jpg')
#resize the image to a 224x224 with the same strategy as in TM2:
#resizing the image to be at least 224x224 and then cropping from the center
size = (224, 224)
image = ImageOps.fit(image, size, Image.ANTIALIAS)

#turn the image into a numpy array
image_array = np.asarray(image)
# Normalize the image
normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
# Load the image into the array
data[0] = normalized_image_array

# run the inference
prediction = model.predict(data)
print(prediction)

[[0.0271141  0.97288597]]


# 使用 Gradio 打包上面的模型來使用

In [ ]:
!pip install gradio

In [ ]:
import random

In [ ]:
def classify(image):
  # Load the model
  model = load_model('keras_model.h5')
  
  image.save(f"{random.randint(0, 99999):05}.jpg")

  # Create the array of the right shape to feed into the keras model
  # The 'length' or number of images you can put into the array is
  # determined by the first position in the shape tuple, in this case 1.
  data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
  #resize the image to a 224x224 with the same strategy as in TM2:
  #resizing the image to be at least 224x224 and then cropping from the center
  size = (224, 224)
  image = ImageOps.fit(image, size, Image.ANTIALIAS)

  #turn the image into a numpy array
  image_array = np.asarray(image)
  # Normalize the image
  normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
  # Load the image into the array
  data[0] = normalized_image_array

  # run the inference
  prediction = model.predict(data)
  labels = ["戴著口罩的Victor", "沒有戴口罩的Victor"]
  return labels[np.argmax(prediction)]

In [ ]:
import gradio as gr

In [ ]:
gr.Interface(classify, inputs=gr.Image(type="pil"), outputs="text").launch(share=True)

Colab notebook detected. To show errors in colab notebook, set `debug=True` in `launch()`
Running on public URL: https://11236.gradio.app

This share link expires in 72 hours. For free permanent hosting, check out Spaces: https://huggingface.co/spaces


(<gradio.routes.App at 0x7f52067e3690>,
 'http://127.0.0.1:7862/',
 'https://11236.gradio.app')

## 練習

請印出 0-15 的二進位數值。

In [ ]:
for i in range(16):
  print(f"{i:2} 的二進位是：{i:04b}")

 0 的二進位是：0000
 1 的二進位是：0001
 2 的二進位是：0010
 3 的二進位是：0011
 4 的二進位是：0100
 5 的二進位是：0101
 6 的二進位是：0110
 7 的二進位是：0111
 8 的二進位是：1000
 9 的二進位是：1001
10 的二進位是：1010
11 的二進位是：1011
12 的二進位是：1100
13 的二進位是：1101
14 的二進位是：1110
15 的二進位是：1111


# Scikit-Learn 簡介

## 載入資料集

In [ ]:
from sklearn import datasets

In [ ]:
iris = datasets.load_iris()

In [ ]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
X = iris.data

In [ ]:
y = iris.target

In [ ]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [ ]:
y[0]

0

In [ ]:
len(X)

150

## 拆分訓練集跟測試集

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## 使用 SVM 來做分類

In [ ]:
# 1. 載入模型
from sklearn.svm import SVC

In [ ]:
# 2. 建立模型
clf = SVC()

In [ ]:
# 3. 訓練模型
clf.fit(X_train, y_train)

SVC()

In [ ]:
# 計算模型準確度 (Accuracy)
clf.score(X_test, y_test)

0.9666666666666667

In [ ]:
# 4. 使用模型
clf.predict(X_test)

array([2, 1, 2, 0, 0, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 0, 0, 1, 2, 1, 0, 1,
       1, 2, 0, 0, 2, 2, 0, 1])